version: '3'

services:
  db:
    container_name: mysql_zooniverse
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: zooniverse_dev
      MYSQL_USER: zooniverse_web
      MYSQL_PASSWORD: test-password#1
    ports:
       - "40001:3306"
  web:
    container_name: dg_zooniverse
    build: ./
    command: >
      bash -c "mkdir -p log
      && pip3 install GPy
      && cp -r extern/acton /usr/local/lib/python3.6/site-packages/
      && python3 development-manage.py migrate
      && python3 development-manage.py setup
      && python3 development-manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/code
      - ./zooniverse_web/static/:/static/
      - ./media/:/media/
    ports:
      - "8000:8000"
    depends_on:
      - db
