# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install python
          command: |
            sudo apt-get update -qq
            sudo apt-get install -y -qq --no-install-recommends python-dev python python-pip


      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Upgrade pip
          command: |
            export PATH=~/.local/bin/:$PATH
            pip3 install --user --upgrade pip

      - run:
          name: install dependencies
          command: |
            export PATH=~/.local/bin/:$PATH
            python3 -m venv venv3
            . venv3/bin/activate
            pip3 install -r requirements.txt
            cp -r extern/acton venv3/lib/python3.6/site-packages/
            sudo chmod -R 777 /media/

      - save_cache:
          paths:
            - ./venv3
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run tests!
      # this example uses Django's built-in test-runner
      # other common Python testing frameworks include pytest and nose
      # https://pytest.org
      # https://nose.readthedocs.io
      - run:
          name: run Python 3 Tests
          command: |
            . venv3/bin/activate
            python3 manage.py test

      - store_artifacts:
          path: test-reports
          destination: test-reports
